### ISSUE TITLE
Feature: Change format of  "0.0" value for unentered weight

### ISSUE THREAD

**Issue by sh0nuff** [blind-coder/hackersdietoffline#2]
Everytime I enter my weight, it puts the cursor at the beginning of the "0.0" value, so I end up putting in "1800.0" instead of 180, which messes with the UI.

Recommended changing the 0.0 value to be a placeholder than when tapped disappears and allows weight to be entered vs having to select the 0.0, delete, then entered.

Sorry if this sounds confusing =)

**Comment by blind-coder** [comment]
I have added fixes for both of your reports, can you test https://www.benjamin-schieder.de/downloads/hackersdiet/HackersDiet_20241120_signed.apk if it fixes them for you?

**Comment by sh0nuff** [comment]
This works great! Thanks!
